# Generated by Django 5.1.6 on 2025-02-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='pdf',
            field=models.FileField(default='default.pdf', upload_to='notes_pdfs/'),
            preserve_default=False,
        ),
    ]
