# Generated by Django 5.1.6 on 2025-02-14 11:56

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_note_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='file',
        ),
        migrations.AlterField(
            model_name='note',
            name='pdf',
            field=models.FileField(upload_to='notes_pdfs/', validators=[content.models.validate_pdf]),
        ),
    ]
