# Generated by Django 5.1.6 on 2025-02-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_recordedvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordedvideo',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recordedvideo',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='recordedvideo',
            name='video',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
