# Generated by Django 5.1.6 on 2025-02-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_roadmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordedvideo',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recordedvideo',
            name='video_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='recordedvideo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
